### ISSUE TITLE
CORS policy API

### ISSUE THREAD

**Issue by x00x0x00x** [n-y-z-o/nyzoVerifier#18]
This is a proposal to add a **Access-Control-Allow-Origin=*** header to the API endpoints. This would allow a wider variety of applications to use the API.

While a browser extension may be an exception to the rule in that it allows such requests to take place (and it is peculiar that it does), most modern day browsers actively enforce the CORS policy and local requests can't be made to the API endpoints.

On the right, the request from the Nyzo tip extension, which doesn't get blocked by CORS policy.
On the left, the request from a local index.html file, which does get blocked by the CORS policy.

I made sure to use the same XMLHttpRequest structure, copied over from the extension, but the results do differ.

![unknown (1)](https://user-images.githubusercontent.com/42121860/81463694-c3510480-91bb-11ea-9d61-8f69a2392f2d.png)
![unknown](https://user-images.githubusercontent.com/42121860/81463696-c3e99b00-91bb-11ea-85bc-03ae1b080e18.png)

**Comment by n-y-z-o** [comment]
Thank you for this suggestion. This has been implemented in version 583, and it is deployed to https://client.nyzo.co.

Version 583 is expected to be released tomorrow.

**Comment by n-y-z-o** [comment]
Version 583 has been released: https://tech.nyzo.co/releaseNotes/v583.

**Comment by l-u-f-o** [comment]
@n-y-z-o seems like this is still an issue. https://client.nyzo.co/frozenEdge for example does not return the Access-Control-Allow-Origin=* header.

**Comment by EggPool** [comment]
Likely some glue code missing between layers.

Also, after a quick look it seems the client could almost be able to return proper Json, there is code already to return such payload (with application/json Content-Type), just this is apparently not used.

It would be great to either
- have endpoints with an extra .json return Json output instead of the html
  https://client.nyzo.co/frozenEdge.json
- and/or read and use "Accept: application/json" header and switch to Json output.

I did not found an existing way of switching to Json. Being dependent of custom formatted html to extract data on the client side is a repeated pain.

**Comment by n-y-z-o** [comment]
All of the endpoints automatically render as HTML and as JSON. The `Access-Control-Allow-Origin=*` header is set for all API endpoints.

For any endpoint, prefix with `/api` to get the JSON version. In this case, it would be:

https://client.nyzo.co/api/frozenEdge

**Comment by EggPool** [comment]
Awesome, missed that!

Thanks!!!
