### ISSUE TITLE
Is it no longer updated?

### ISSUE THREAD

**Issue by awshrb** [n-y-z-o/nyzoVerifier#47]

**Comment by n-y-z-o** [comment]
There has been no need for updates to the verifier in a long time. 

We have been monitoring issues with slow entrance rate into the cycle, but this is not correctable with updates to the verifier. This is simply due to the small size of the queue and poor configuration of many in-queue verifiers.

The next update will likely be the blockchain version 3 update (https://tech.nyzo.co/teamTechnologyProposals/nttp9), which will most importantly consolidate the seed account into the cycle account and use the cycle account to supplement transaction fees and ensure a minimum per-block verifier reward.

**Comment by awshrb** [comment]
Very happy to hear the dev's response.
When will version 3 be online?
Almost lost confidence recently because there is no news from the developer.

**Comment by n-y-z-o** [comment]
We don't yet have a planned release date for version 3, but it will leave plenty of room for verifiers to update, and it will be long before the current seed transactions run out.
